import { Font, Template } from './types';

export const FONTS: Font[] = [
  { name: 'Roboto', value: 'Roboto, sans-serif' },
  { name: 'Open Sans', value: '"Open Sans", sans-serif' },
  { name: 'Lato', value: 'Lato, sans-serif' },
  { name: 'Montserrat', value: 'Montserrat, sans-serif' },
  { name: 'Merriweather', value: 'Merriweather, serif' },
  { name: 'Playfair Display', value: '"Playfair Display", serif' },
];

export const TEMPLATES: Template[] = [
  // --- Corporate & Clean ---
  { name: 'Classic Blue', data: { backgroundColor: '#eef2ff', textColor: '#1e3a8a', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Steel Gray', data: { backgroundColor: '#f8fafc', textColor: '#334155', fontFamily: 'Roboto', layout: 'left' } },
  { name: 'Executive White', data: { backgroundColor: '#ffffff', textColor: '#111827', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Forest Green', data: { backgroundColor: '#f0fdf4', textColor: '#14532d', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Modern Tech', data: { backgroundColor: '#f3f4f6', textColor: '#1e40af', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Simple Beige', data: { backgroundColor: '#f5f5f4', textColor: '#3f3f46', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Professional Teal', data: { backgroundColor: '#f0f9ff', textColor: '#155e75', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Subtle Slate', data: { backgroundColor: '#f1f5f9', textColor: '#334155', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Maroon Corporate', data: { backgroundColor: '#fef2f2', textColor: '#881337', fontFamily: 'Merriweather', layout: 'center' } },
  { name: 'Light Indigo', data: { backgroundColor: '#eef2ff', textColor: '#3730a3', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Clean Mint', data: { backgroundColor: '#f0fdfa', textColor: '#047857', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Stone Professional', data: { backgroundColor: '#fafaf9', textColor: '#44403c', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Sky Blue', data: { backgroundColor: '#f0f9ff', textColor: '#075985', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Amber Light', data: { backgroundColor: '#fffbeb', textColor: '#b45309', fontFamily: 'Merriweather', layout: 'center' } },
  { name: 'Rose Tint', data: { backgroundColor: '#fff1f2', textColor: '#9f1239', fontFamily: 'Playfair Display', layout: 'left' } },

  // --- Bold & Creative ---
  { name: 'Vibrant Orange', data: { backgroundColor: '#ffedd5', textColor: '#c2410c', fontFamily: 'Montserrat', layout: 'center' } },
  { name: 'Electric Lime', data: { backgroundColor: '#f7fee7', textColor: '#3f6212', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Bold Red', data: { backgroundColor: '#fee2e2', textColor: '#991b1b', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Startup Yellow', data: { backgroundColor: '#fefce8', textColor: '#854d0e', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Creative Fuchsia', data: { backgroundColor: '#fdf4ff', textColor: '#a21caf', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Aqua Splash', data: { backgroundColor: '#ecfeff', textColor: '#0e7490', fontFamily: 'Roboto', layout: 'left' } },
  { name: 'Hot Pink', data: { backgroundColor: '#fdf2f8', textColor: '#be185d', fontFamily: 'Montserrat', layout: 'center' } },
  { name: 'Cyber Yellow', data: { backgroundColor: '#fef9c3', textColor: '#713f12', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Purple Pop', data: { backgroundColor: '#faf5ff', textColor: '#7e22ce', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Bright Teal', data: { backgroundColor: '#ccfbf1', textColor: '#0f766e', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Tangerine', data: { backgroundColor: '#fff7ed', textColor: '#ea580c', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Zesty Green', data: { backgroundColor: '#f0fdf4', textColor: '#16a34a', fontFamily: 'Open Sans', layout: 'center' } },
  { name: 'Rich Magenta', data: { backgroundColor: '#fdf4ff', textColor: '#c026d3', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Ocean Blue', data: { backgroundColor: '#eff6ff', textColor: '#1d4ed8', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Goldenrod', data: { backgroundColor: '#fefce8', textColor: '#ca8a04', fontFamily: 'Merriweather', layout: 'center' } },

  // --- Elegant & Minimal ---
  { name: 'Classic Ivory', data: { backgroundColor: '#fefce8', textColor: '#3f3f46', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Rose Gold', data: { backgroundColor: '#fff1f2', textColor: '#881337', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Minimalist Sand', data: { backgroundColor: '#fdfdfd', textColor: '#57534e', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Lavender Haze', data: { backgroundColor: '#f5f3ff', textColor: '#5b21b6', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Soft Peach', data: { backgroundColor: '#fff7ed', textColor: '#9a3412', fontFamily: 'Playfair Display', layout: 'left' } },
  { name: 'Pistachio Green', data: { backgroundColor: '#f0fdf4', textColor: '#166534', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Powder Blue', data: { backgroundColor: '#f0f9ff', textColor: '#0c4a6e', fontFamily: 'Open Sans', layout: 'center' } },
  { name: 'Warm Taupe', data: { backgroundColor: '#f5f5f4', textColor: '#57534e', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Blush Pink', data: { backgroundColor: '#fdf2f8', textColor: '#9d174d', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Light Champagne', data: { backgroundColor: '#fcfce8', textColor: '#78350f', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Cool Silver', data: { backgroundColor: '#f8fafc', textColor: '#475569', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Muted Clay', data: { backgroundColor: '#fef2f2', textColor: '#8f2c2c', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Dusty Rose', data: { backgroundColor: '#fef1f2', textColor: '#902d4f', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Sage Green', data: { backgroundColor: '#f3f4f6', textColor: '#374151', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Elegant Cream', data: { backgroundColor: '#fffbeb', textColor: '#7c2d12', fontFamily: 'Merriweather', layout: 'left' } },

  // --- Dark & Moody ---
  { name: 'Deep Indigo', data: { backgroundColor: '#312e81', textColor: '#e0e7ff', fontFamily: 'Lato', layout: 'left' } },
  { name: "Hunter's Green", data: { backgroundColor: '#14532d', textColor: '#dcfce7', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Charcoal & Mint', data: { backgroundColor: '#1e293b', textColor: '#a7f3d0', fontFamily: 'Roboto', layout: 'left' } },
  { name: 'Midnight Blue', data: { backgroundColor: '#1e3a8a', textColor: '#dbeafe', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Black & Gold', data: { backgroundColor: '#171717', textColor: '#fde047', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Slate & Cyan', data: { backgroundColor: '#334155', textColor: '#67e8f9', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Dark Plum', data: { backgroundColor: '#581c87', textColor: '#f3e8ff', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Espresso', data: { backgroundColor: '#44403c', textColor: '#f5f5f4', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Crimson Night', data: { backgroundColor: '#991b1b', textColor: '#fee2e2', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Graphite', data: { backgroundColor: '#262626', textColor: '#e5e5e5', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Teal Deep', data: { backgroundColor: '#115e59', textColor: '#ccfbf1', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Navy & Silver', data: { backgroundColor: '#1e3a8a', textColor: '#e5e7eb', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Ruby Red Dark', data: { backgroundColor: '#881337', textColor: '#fff1f2', fontFamily: 'Merriweather', layout: 'center' } },
  { name: 'Obsidian', data: { backgroundColor: '#020617', textColor: '#94a3b8', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Forest Night', data: { backgroundColor: '#0f172a', textColor: '#a3e635', fontFamily: 'Roboto', layout: 'center' } },
  
  // --- Light & Vibrant ---
  { name: 'Sunshine', data: { backgroundColor: '#fef3c7', textColor: '#92400e', fontFamily: 'Montserrat', layout: 'left' } },
  { name: 'Aqua Fresh', data: { backgroundColor: '#ecfeff', textColor: '#0891b2', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Bright Lavender', data: { backgroundColor: '#f5f3ff', textColor: '#6d28d9', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Spring Green', data: { backgroundColor: '#dcfce7', textColor: '#16a34a', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Pastel Pink', data: { backgroundColor: '#fdf2f8', textColor: '#db2777', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Vibrant Sky', data: { backgroundColor: '#dbeafe', textColor: '#2563eb', fontFamily: 'Roboto', layout: 'left' } },
  { name: 'Lemon Zest', data: { backgroundColor: '#fefce8', textColor: '#a16207', fontFamily: 'Montserrat', layout: 'center' } },
  { name: 'Coral Reef', data: { backgroundColor: '#fff1f2', textColor: '#e11d48', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Kiwi Green', data: { backgroundColor: '#f0fdf4', textColor: '#15803d', fontFamily: 'Open Sans', layout: 'center' } },
  { name: 'Bright Purple', data: { backgroundColor: '#f3e8ff', textColor: '#9333ea', fontFamily: 'Montserrat', layout: 'center' } },
  { name: 'Icy Blue', data: { backgroundColor: '#e0f2fe', textColor: '#0369a1', fontFamily: 'Roboto', layout: 'left' } },
  { name: 'Melon', data: { backgroundColor: '#fff7ed', textColor: '#c2410c', fontFamily: 'Lato', layout: 'center' } },
  { name: 'Fresh Mint', data: { backgroundColor: '#d1fae5', textColor: '#047857', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'Electric Blue', data: { backgroundColor: '#dbeafe', textColor: '#1e40af', fontFamily: 'Montserrat', layout: 'center' } },
  { name: 'Sunny Orange', data: { backgroundColor: '#ffedd5', textColor: '#f97316', fontFamily: 'Roboto', layout: 'left' } },
  { name: 'Cherry Blossom', data: { backgroundColor: '#fef1f2', textColor: '#be185d', fontFamily: 'Playfair Display', layout: 'center' } },
  { name: 'Limeade', data: { backgroundColor: '#ecfccb', textColor: '#4d7c0f', fontFamily: 'Open Sans', layout: 'left' } },
  
  // Add a few more dark ones for good measure
  { name: 'Midnight Emerald', data: { backgroundColor: '#064e3b', textColor: '#a7f3d0', fontFamily: 'Merriweather', layout: 'left' } },
  { name: 'Deep Space', data: { backgroundColor: '#1f2937', textColor: '#93c5fd', fontFamily: 'Montserrat', layout: 'center' } },
  { name: 'Royal Dark Blue', data: { backgroundColor: '#312e81', textColor: '#c7d2fe', fontFamily: 'Lato', layout: 'left' } },
  { name: 'Volcanic Rock', data: { backgroundColor: '#4b5563', textColor: '#fef9c3', fontFamily: 'Roboto', layout: 'center' } },
  { name: 'Black & White', data: { backgroundColor: '#000000', textColor: '#ffffff', fontFamily: 'Open Sans', layout: 'left' } },
  { name: 'White & Black', data: { backgroundColor: '#ffffff', textColor: '#000000', fontFamily: 'Open Sans', layout: 'left' } },
];
